//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elections_POC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elector
    {
        public int ElectorId { get; set; }
        public string IdentificationNumber { get; set; }
        public Nullable<int> PollingStationsId { get; set; }
        public string IdentificationImg { get; set; }
        public string IdentificationTypeId { get; set; }
        public Nullable<int> FingerPrintId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
