//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elections_POC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FingerPrint
    {
        public int Serial { get; set; }
        public string UserID { get; set; }
        public int FingerIndex { get; set; }
        public byte[] Template1 { get; set; }
        public byte[] Template2 { get; set; }
        public string Memo { get; set; }
    }
}
